# Generated by Django 3.2.6 on 2021-08-10 18:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Post date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='intro',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
